version: "3"

services:
  nginx:
    image: nginx:1.15.12
    command: nginx
    volumes:
      - ./public:/var/www/public
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"